# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76e688470a1abad58bce949418b3dc512703fe7c61f6fe23405db835534aa39675442a14cdbc9394f2c1532e6bec8d7e0d61f875396e91cd4753c17b73b4c589

test:
  secret_key_base: bf4518744cfd688f68516fa6275aae9cc9a7d7aa636b183a9c5c030cb51b596c3bc9154a4b5eca0def7d28bc743ffe686d6645c2a1f6a4c2c926da2dccd6e05a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
